
CREATE TABLE STORAGES(
ID_STORAGE NUMBER,
CONSTRAINT ID_STORAGE PRIMARY KEY (ID_STORAGE),
FORMATS_SUPPORTED NVARCHAR2(250),
STORAGE_COUNTY NVARCHAR2(50),
STORAGE_SIZE NUMBER
);

CREATE SEQUENCE SEQ_STORAGE MINVALUE 500 MAXVALUE 4000  START WITH 501 INCREMENT BY 1;