CREATE TABLE ITEM(
ID NUMBER,
CONSTRAINT ID PRIMARY KEY (ID),
NAME NVARCHAR2(50),
DATE_CREATED TIMESTAMP,
LAST_UPDATED_DATE TIMESTAMP,
DESCRIPTION NVARCHAR2(250)
);

CREATE SEQUENCE ITEM_SEQ MINVALUE 1000 MAXVALUE 9999 START WITH 1000 INCREMENT BY 1;