CREATE TABLE FILES(
ID_FILE NUMBER,
CONSTRAINT ID_FILE PRIMARY KEY (ID_FILE),
FILE_NAME NVARCHAR2(50) NOT NULL,
FILE_FORMAT NVARCHAR2(50) NOT NULL,
FILE_SIZE NUMBER,
STORAGE_ID NUMBER,
CONSTRAINT ID_STORAGE_FK FOREIGN KEY (STORAGE_ID) REFERENCES STORAGES(ID));


CREATE SEQUENCE SEQ_FILE MINVALUE 1000 MAXVALUE 4000  START WITH 1001 INCREMENT BY 1;