CREATE TABLE STORAGE(
ID NUMBER,
CONSTRAINT ID_STORAGE PRIMARY KEY (ID),
FORMATS_SUPPORTED NVARCHAR2(250),
STORAGE_COUNTY NVARCHAR2(50),
STORAGE_SIZE NUMBER
);

CREATE SEQUENCE SEQ_STORAGE MINVALUE 300 MAXVALUE 4000  START WITH 301 INCREMENT BY 1;