CREATE TABLE JOIN_FLIGHT_PASSENGER(
FLIGHT_ID NUMBER,
CONSTRAINT ID_FLIGHT_FK FOREIGN KEY (FLIGHT_ID) REFERENCES FLIGTH(ID),
PASSENGER_ID NUMBER,
CONSTRAINT ID_PASSENGER_FK FOREIGN KEY (PASSENGER_ID) REFERENCES PASSENGER(ID)
)