CREATE TABLE PLANE(
ID NUMBER,
CONSTRAINT ID_PLANE PRIMARY KEY (ID),
MODEL NVARCHAR2(20),
CODE NVARCHAR2(20),
YEAR_PRODUCED TIMESTAMP,
AVG_FUEL_CONSUMPTION DOUBLE PRECISION
);

CREATE SEQUENCE PLANE_SEQ MINVALUE 1000 MAXVALUE 9999 START WITH 1000 INCREMENT BY 1;
