CREATE TABLE FLIGHT(
ID NUMBER,
CONSTRAINT ID_FLIGHT PRIMARY KEY (ID),
PLANE_ID NUMBER,
CONSTRAINT ID_PLANE_FK FOREIGN KEY (PLANE_ID) REFERENCES PLANE(ID),
DATEFLIGHT TIMESTAMP,
CITYFROM NVARCHAR2(20),
CITYTO NVARCHAR2(20)
);

CREATE SEQUENCE FLIGHT_SEQ MINVALUE 1000 MAXVALUE 9999 START WITH 1000 INCREMENT BY 1;