CREATE TABLE PASSENGER(
ID NUMBER,
CONSTRAINT ID_PASSENGER PRIMARY KEY (ID),
LASTNAME NVARCHAR2(20),
NATIONALITY NVARCHAR2(20),
DATEOFBIRTH TIMESTAMP,
PASPORTCODE NVARCHAR2(20)
);

CREATE SEQUENCE PASSENGER_SEQ MINVALUE 1000 MAXVALUE 9999 START WITH 1000 INCREMENT BY 1;
